/*
*********************************************************************************************************
*
*                                      MCU: MC9S12XS128MAL - 112Pin
*                                      OSC: 16.000MHz
*                                      BUS: 32.0MHz
*								  Describe:	ATD0 八路
*
* File : ATD.h
* By   : atao
*********************************************************************************************************
*/
#ifndef ATD_H_
#define ATD_H_

void ATD0_Init(void);

unsigned int ATD0_Read(unsigned char);

#endif
